version: '3'

services:
  web:
    container_name: web
    restart: always
    build: .
    command: bash -c "python main.py run -h 0.0.0.0"
    networks:
      - my-network
    ports:
      - 5008:5008
    volumes:
      - .:/app
    depends_on:
      - main_db
      - test_db

  main_db:
    container_name: main_db
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0672934823a
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  test_db:
    container_name: test_db
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0672934823a
      POSTGRES_DB: test_db
    ports:
      - 5431:5432
    networks:
      - my-network
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/test_data

volumes:
  postgres-data: {}

networks:
  my-network:
